### ISSUE TITLE
Spaces between call arguments

### ISSUE THREAD

**Issue by techtonik** [Calinou/godot-style-guide#1]
Should there be spaces in function calls?

```
OS::get_singleton()->print("Passed %i of %i tests\n",passed,count);
```

Vs:

```
OS::get_singleton()->print("Passed %i of %i tests\n", passed, count);
```

**Comment by Calinou** [comment]
Yes, very likely, it's more readable this way.

https://github.com/Calinou/godot-style-guide/commit/f2f90e7a7077f5c8c89fa7002bcf8e7944fdef4e
