### ISSUE TITLE
Convention for importing other scripts

### ISSUE THREAD

**Issue by arypbatista** [Calinou/godot-style-guide#2]
Hi,

On my scripts I am using a convention pretty similar to what NodeJS uses for their module system.

When using `preload` to load a script, I assign the script to a variable defined with keyword `const`. Since each script is a class, I name the variable using camelcase. But we could think of it a bit more. 

```GDScript
const ClassName = preload('class_name.gd')
```

Let's say I am programming the model behind my game, where a character has an inventory with items, and the character has the hability to craft new items. My character extends an abstract entity class which has some common behavior between NPCs and him.

```GDScript
extends 'entity.gd'

const ItemBag = preload('./inventory/item_bag.gd')
const Item    = preload('./inventory/item.gd')

var inventory

func _init():
  inventory = ItemBag.new()
  inventory.add(new Item('Water'))

func craft(recipe):
  # Validate recipe requirements
  # Craft the thing
```

So, this is the basic convention I propose. In this way you get all preloads on top of the file and it is really similar to NodeJS' `require` function or to Python's `import` keywords.

An extension to this would be how to treat single instance scripts (not singleton, that needs to be done using autoload or a handmade script loader I think). Unfortunately `const` keyword does not allow instancing. So to create a singleton I am using the `var` keyword. Variable name defined with camelcase.

```GDScript
extends Node2D

var Astronomy = preload('./astronomy.gd').new()

func _init():
  print(Astronomy.next_calendar_full_moon())
```

Any thoughts?

**Comment by bojidar-bg** [comment]
That's how we have it on https://github.com/KOBUGE-Games/resources/blob/master/STYLE-GUIDE.md

> const-s are in all-uppercase SNAKE_CASE, unless they hold a preloaded class, in which case they follow the instructions for inner classes

**Comment by Calinou** [comment]
Closing, as this style guide should now be considered deprecated (see the [official GDScript style guide](http://docs.godotengine.org/en/latest/getting_started/scripting/gdscript/gdscript_styleguide.html)).
